name: CI/CD Workflow
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir mensaje
        run: echo "Hola, este es un workflow simple que corre al hacer push" 
        
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Lint del código
        run: npm run lint

      - name: Ejecutar pruebas con cobertura
        run: npm test -- --coverage

      - name: Publicar reporte de cobertura
        uses: actions/upload-artifact@v3
        with:
          name: cobertura-jest
          path: coverage/

      - name: Simular despliegue
        run: echo "Despliegue simulado. La aplicación pasó pruebas y Lint correctamente."
